services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.0
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-mysql
      KC_DB_USERNAME: csh
      KC_DB_PASSWORD: csh123
      KC_BOOTSTRAP_ADM0N_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:9.3.0
    container_name: keycloak-mysql
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: csh
      MYSQL_PASSWORD: csh123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "4307:3306"
    volumes:
      - keycloak-mysql:/var/lib/mysql
    restart: unless-stopped

volumes:
  keycloak-mysql:
