services:
  mysql:
    image: mysql:9.3.0
    container_name: mysql-inventory-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventory_service
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
